apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: spark
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=git://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@github.com/Zahidmad/apachespark.git"
    - "--destination=zramazanli/kaniko-demo-image:1.0"
    - "--dockerfile=kubernetes/dockerfiles/spark/Dockerfile"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: dockercred
      items:
        - key: .dockerconfigjson
          path: config.json
